/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iznan_bookapps_MyNDK */

#ifndef _Included_com_iznan_bookapps_MyNDK
#define _Included_com_iznan_bookapps_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iznan_bookapps_MyNDK
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iznan_bookapps_MyNDK_getMyString
  (JNIEnv *, jclass);

/*
 * Class:     com_iznan_bookapps_MyNDK
 * Method:    getApiKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iznan_bookapps_MyNDK_getApiKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
